// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6mEFS6DELUM1ASLVHkgl8NXBXfzQwen8',
    appId: '1:820375406013:web:1a0ae33cc3d239c909fed4',
    messagingSenderId: '820375406013',
    projectId: 'finance-app-33581',
    authDomain: 'finance-app-33581.firebaseapp.com',
    storageBucket: 'finance-app-33581.appspot.com',
    measurementId: 'G-SB6P9QLD35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoZs4zoyffTCpGjR6UpqsADcLtORNdceA',
    appId: '1:820375406013:android:9a623819fd6c66d309fed4',
    messagingSenderId: '820375406013',
    projectId: 'finance-app-33581',
    storageBucket: 'finance-app-33581.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnpl8J-5jhkENCC67bbc1FDqRKuqRXWvI',
    appId: '1:820375406013:ios:90138fb88c6f677209fed4',
    messagingSenderId: '820375406013',
    projectId: 'finance-app-33581',
    storageBucket: 'finance-app-33581.appspot.com',
    iosClientId:
        '820375406013-rq7ln8jhu02tr6cokccaeu3k36q726ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.finance_app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnpl8J-5jhkENCC67bbc1FDqRKuqRXWvI',
    appId: '1:820375406013:ios:90138fb88c6f677209fed4',
    messagingSenderId: '820375406013',
    projectId: 'finance-app-33581',
    storageBucket: 'finance-app-33581.appspot.com',
    iosClientId:
        '820375406013-rq7ln8jhu02tr6cokccaeu3k36q726ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.finance_app',
  );
}
